---
# tasks file for kibana image, static config
- name: update
  apt:
    update_cache: yes
  become: true

- name: upgrade system
  apt:
    upgrade: yes
    upgrade: dist
    update_cache: true
  become: true

- name: run script for kibana
  script: ~/dangerzone/packer/ansible/roles/kibana/files/kibana.sh
  become: true
  
- name: upload config for kibana
  copy:
    src: ~/dangerzone/packer/ansible/roles/kibana/files/kibana.yml
    dest: /etc/kibana/kibana.yml
    owner: okhab
    mode: '0644'
  become: true
  
- name: upload config for nginx site
  copy:
    src: ~/dangerzone/packer/ansible/roles/kibana/files/sahay.pp.ua
    dest: /etc/nginx/sites-available/sahay.pp.ua
    owner: okhab
    mode: '0644'
  become: true  
  
- name: sites-available to sites-enabled
  shell: ln -s /etc/nginx/sites-available/sahay.pp.ua /etc/nginx/sites-enabled/sahay.pp.ua
  become: true
  
- name: enable nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: true
  
- name: enable kibana
  service:
    name: kibana
    state: started
    enabled: yes
  become: true  
  
  
  
