# Kibana is served by a back end server. This setting specifies the port to us>
#server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and>
# The default is 'localhost', which usually means remote machines will not be >
# To allow connections from remote users, set this parameter to a non-loopback>
#server.host: 35.211.166.19
# Enables you to specify a path to mount Kibana at if you are running behind a>
# Use the `server.rewriteBasePath` setting to tell Kibana if it should remove >
# from requests it receives, and to prevent a deprecation warning at startup.
# This setting cannot end in a slash.
#server.basePath: ""

# Specifies whether Kibana should rewrite requests that are prefixed with
# `server.basePath` or require that they are rewritten by your reverse proxy.
# This setting was effectively always `false` before Kibana 6.3 and will
# default to `true` starting in Kibana 7.0.
#server.rewriteBasePath: false

# Specifies the public URL at which Kibana is available for end users. If
# `server.basePath` is configured this URL should end with the same basePath.
#server.publicBaseUrl: ""

# The maximum payload size in bytes for incoming server requests.
#server.maxPayloadBytes: 1048576

# The Kibana server's name.  This is used for display purposes.
#server.name: "your-hostname"

# The URLs of the Elasticsearch instances to use for all your queries.
elasticsearch.hosts: ["http://10.53.10.18:9200","http://10.53.10.19:9200","http://10.53.10.20:9200"]

# Kibana uses an index in Elasticsearch to store saved searches, visualization>
# dashboards. Kibana creates a new index if the index doesn't already exist.
#kibana.index: ".kibana"

# The default application to load.
#kibana.defaultAppId: "home"

# If your Elasticsearch is protected with basic authentication, these settings>
# the username and password that the Kibana server uses to perform maintenance>
# index at startup. Your Kibana users still need to authenticate with Elastics>
# is proxied through the Kibana server.
#elasticsearch.username: "kibana_system"
#elasticsearch.password: "pass"
