---
# tasks file for wp-mon, derived from wordpress
- name: update
  apt:
    update_cache: yes
  become: true

- name: upgrade system
  apt:
    upgrade: yes
    upgrade: dist
    update_cache: true
  become: true

- name: install php
  apt: 
    name:
    - php
    - php-curl
    - php-common
    - php-mbstring
    - php-gd
    - php-intl
    - php-xml
    - php-mysql
    - php-fpm
    - php-zip 
    state: present
  become: true
  
- name: install mariadb
  apt:
    name:
    - mariadb-server
    - mariadb-client
    state: present
  become: true

- name: install apache
  apt: 
    name: apache2 
    state: present
  become: true

- name: enable apache
  service:
    name: apache2
    enabled: yes

- name: install unzip
  apt:
    name: unzip
    state: present
  become: true
   
- name: upload config for apache default site
  ansible.builtin.copy:
    src: ~/dangerzone/packer/ansible/roles/wp-mon/files/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: okhab
    mode: '0644'
  become: true

- name: upload config for apache dir.conf
  ansible.builtin.copy:
    src: ~/dangerzone/packer/ansible/roles/wp-mon/files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: okhab
    mode: '0644'
  become: true

#- name: upload script for installing gcsfuse
#  ansible.builtin.copy:
#    src: ~/dangerzone/packer/ansible/roles/wordpress/files/gcsfuse-install.sh
#    dest: /tmp/gcsfuse-install.sh
#    owner: okhab
#    mode: '0755'
#  become: true

- name: make dir for creds
  shell: mkdir -p /etc/google/auth
  become: true

- name: upload creds
  ansible.builtin.copy:
    src: /home/sahay/dangerzone/restricted/okhab-education-25433-255496390538.json
    dest: /etc/google/auth/application_default_credentials.json
    owner: root
    mode: '0400'
  become: true

- name: system variable for creds
  shell: GOOGLE_APPLICATION_CREDENTIALS="/etc/google/auth/application_default_credentials.json"

#- name: run script for installing gcsfuse
#     script: home/sahay/dangerzone/packer/ansible/roles/wordpress/files/gcsfuse-install.sh
#     script: /tmp/gcsfuse-install.sh
#  shell: /tmp/gcsfuse-install.sh

#- name: upload gcfuse.conf
#  ansible.builtin.copy:
#    src: ~/dangerzone/packer/ansible/roles/wordpress/files/fuse.conf
#    dest: /etc/fuse.conf
#    owner: okhab
#    mode: '0644'
#  become: true

#- name: upload script for running gcsfuse
#  ansible.builtin.copy:
#    src: ~/dangerzone/packer/ansible/roles/wordpress/files/gcsfuse-run.sh
#    dest: /tmp/gcsfuse-run.sh
#    owner: okhab
#    mode: '0755'

#- name: run script for running gcsfuse
#  script: /home/sahay/dangerzone/packer/ansible/roles/wordpress/files/gcsfuse-run.sh

#- name: upload script for wordpress
#  ansible.builtin.copy:
#    src: ~/dangerzone/packer/ansible/roles/wordpress/files/wordpress-install.sh
#    dest: /tmp/wordpress-install.sh
#    owner: okhab
#    mode: '0755'

- name: run script for wordpress
  script: /home/sahay/dangerzone/packer/ansible/roles/wp-mon/files/wordpress-install.sh
  become: true
