---
# tasks file for wp-filebeat, derived from wordpress
- name: update
  apt:
    update_cache: yes
  become: true

- name: upgrade system
  apt:
    upgrade: yes
    upgrade: dist
    update_cache: true
  become: true

- name: install php
  apt: 
    name:
    - php
    - php-curl
    - php-common
    - php-mbstring
    - php-gd
    - php-intl
    - php-xml
    - php-mysql
    - php-fpm
    - php-zip 
    state: present
  become: true
  
- name: install mariadb
  apt:
    name:
    - mariadb-server
    - mariadb-client
    state: present
  become: true

- name: install apache
  apt: 
    name: apache2 
    state: present
  become: true

- name: enable apache
  service:
    name: apache2
    enabled: yes

- name: install unzip
  apt:
    name: unzip
    state: present
  become: true
   
- name: upload config for apache default site
  copy:
    src: ~/dangerzone/packer/ansible/roles/wp-filebeat/files/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    owner: okhab
    mode: '0644'
  become: true

- name: upload config for apache dir.conf
  copy:
    src: ~/dangerzone/packer/ansible/roles/wp-filebeat/files/dir.conf
    dest: /etc/apache2/mods-enabled/dir.conf
    owner: okhab
    mode: '0644'
  become: true

- name: make dir for creds
  shell: mkdir -p /etc/google/auth
  become: true

- name: upload creds
  ansible.builtin.copy:
    src: ~/dangerzone/restricted/okhab-education-25433-255496390538.json
    dest: /etc/google/auth/application_default_credentials.json
    owner: root
    mode: '0400'
  become: true

- name: system variable for creds
  shell: GOOGLE_APPLICATION_CREDENTIALS="/etc/google/auth/application_default_credentials.json"

- name: run script for wordpress
  script: ~/dangerzone/packer/ansible/roles/wp-filebeat/files/wordpress-install.sh
  become: true
  
- name: run script for filebeat
  script: ~/dangerzone/packer/ansible/roles/wp-filebeat/files/filebeat.sh
  become: true
  
- name: upload config for filebeat
  copy:
    src: ~/dangerzone/packer/ansible/roles/wp-filebeat/files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    mode: '0644'
  become: true
  
- name: enable filebeat
  service:
    name: filebeat
    state: restarted
    enabled: yes
  become: true

