---
# tasks file for logstash image, static config
- name: update
  apt:
    update_cache: yes
  become: true

- name: upgrade system
  apt:
    upgrade: yes
    upgrade: dist
    update_cache: true
  become: true

- name: run script for logstash
  script: ~/dangerzone/demo/packer/ansible/roles/logstash/files/logstash.sh
  become: true
  
- name: upload config for logstash
  copy:
    src: ~/dangerzone/demo/packer/ansible/roles/logstash/files/logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    owner: okhab
    mode: '0644'
  become: true
  
- name: enable logstash
  service:
    name: logstash
    state: started
    enabled: yes
  become: true
